#!/usr/bin/env python3
"""Inspect or prepare the locally installed TWK Lausanne Pan webfont assets."""

from __future__ import annotations

import argparse
import os
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "public" / "audt-fonts"
WEIGHTS = (300, 400, 500, 600, 700)
LICENSE_ACK_ENV = "AUDT_TWK_WEBFONT_LICENSE_CONFIRMED"


@dataclass(frozen=True)
class FontJob:
    source: Path
    destination_name: str
    weight: int
    italic: bool


def get_font_dir() -> Path:
    return Path(
        os.environ.get("AUDT_TWK_FONT_DIR", Path.home() / "Library" / "Fonts")
    ).expanduser()


def build_jobs(font_dir: Path) -> list[FontJob]:
    jobs = [
        FontJob(
            source=font_dir / f"TWKLausannePan-{weight}{suffix}.otf",
            destination_name=output_name(weight, italic),
            weight=weight,
            italic=italic,
        )
        for weight in WEIGHTS
        for italic, suffix in ((False, ""), (True, "Italic"))
    ]
    assert_unique_destinations(jobs)
    return jobs


def assert_unique_destinations(jobs: Iterable[FontJob]) -> None:
    destinations: set[str] = set()
    for job in jobs:
        if job.destination_name in destinations:
            raise ValueError(f"Duplicate font output: {job.destination_name}")
        destinations.add(job.destination_name)


def validate_sources(jobs: Iterable[FontJob]) -> None:
    missing = [str(job.source) for job in jobs if not job.source.is_file()]
    if missing:
        raise FileNotFoundError("Missing TWK Lausanne Pan fonts:\n- " + "\n- ".join(missing))


def output_name(weight: int, italic: bool) -> str:
    style = "italic" if italic else "normal"
    return f"audt-{weight}-{style}.woff"


def read_name(font: object, name_id: int) -> str | None:
    names = getattr(font, "__getitem__")("name").names
    for record in names:
        if record.nameID != name_id:
            continue
        try:
            value = record.toUnicode().strip()
        except UnicodeError:
            continue
        if value:
            return value
    return None


def inspect_fonts(jobs: list[FontJob]) -> None:
    from fontTools.ttLib import TTFont

    validate_sources(jobs)
    for job in jobs:
        font = TTFont(job.source, lazy=True)
        os2 = font.get("OS/2")
        print(job.source.name)
        print(f"  family: {read_name(font, 1) or 'not declared'}")
        print(f"  style: {read_name(font, 2) or 'not declared'}")
        print(f"  fsType: {getattr(os2, 'fsType', 'not declared')}")
        print(f"  embedded license: {read_name(font, 13) or 'not declared'}")
        print(f"  license URL: {read_name(font, 14) or 'not declared'}")
        font.close()

    print(
        "Inspection only: font metadata is not proof of webfont embedding rights. "
        "Review the applicable purchase/license terms before deployment."
    )


def write_woff(source: Path, destination: Path) -> None:
    from fontTools.ttLib import TTFont

    if destination.exists():
        raise FileExistsError(f"Refusing to overwrite duplicate font output: {destination}")
    font = TTFont(source)
    font.flavor = "woff"
    font.save(destination)
    font.close()


def write_stylesheet(jobs: Iterable[FontJob], destination: Path) -> None:
    if destination.exists():
        raise FileExistsError(
            f"Refusing to overwrite duplicate font output: {destination}"
        )

    blocks = ["/* Generated by prepare-audt-fonts.py. Do not edit. */"]
    for job in jobs:
        style = "italic" if job.italic else "normal"
        blocks.append(
            "\n".join(
                (
                    "@font-face {",
                    '  font-family: "audt.ai Sans";',
                    f"  font-style: {style};",
                    f"  font-weight: {job.weight};",
                    "  font-display: swap;",
                    f'  src: url("./{job.destination_name}") format("woff");',
                    "}",
                )
            )
        )

    destination.write_text("\n\n".join(blocks) + "\n", encoding="utf-8")


def prepare_fonts(jobs: list[FontJob]) -> None:
    if os.environ.get(LICENSE_ACK_ENV) != "1":
        raise PermissionError(
            f"Refusing to create deployable webfonts without {LICENSE_ACK_ENV}=1. "
            "Set it only after confirming that the applicable license permits "
            "conversion and hosting on a public web server."
        )

    validate_sources(jobs)
    OUTPUT_DIR.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".audt-fonts-", dir=OUTPUT_DIR.parent))
    backup = OUTPUT_DIR.parent / ".audt-fonts-backup"

    try:
        for job in jobs:
            write_woff(job.source, staging / job.destination_name)
        stylesheet_name = "audt-fonts.css"
        write_stylesheet(jobs, staging / stylesheet_name)

        actual_outputs = {path.name for path in staging.iterdir()}
        expected_outputs = {job.destination_name for job in jobs} | {
            stylesheet_name
        }
        if actual_outputs != expected_outputs:
            raise RuntimeError("Prepared font outputs did not match the expected asset set")

        shutil.rmtree(backup, ignore_errors=True)
        if OUTPUT_DIR.exists():
            OUTPUT_DIR.rename(backup)
        try:
            staging.rename(OUTPUT_DIR)
        except BaseException:
            if backup.exists() and not OUTPUT_DIR.exists():
                backup.rename(OUTPUT_DIR)
            raise
        shutil.rmtree(backup, ignore_errors=True)
    finally:
        shutil.rmtree(staging, ignore_errors=True)

    print(
        f"Prepared {len(jobs)} TWK Lausanne Pan webfonts and their stylesheet "
        f"in {OUTPUT_DIR}"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "command",
        choices=("inspect", "prepare"),
        help="inspect local metadata or prepare deployable WOFF assets",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    jobs = build_jobs(get_font_dir())
    if args.command == "inspect":
        inspect_fonts(jobs)
    else:
        prepare_fonts(jobs)


if __name__ == "__main__":
    main()
